-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 21:42:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`students` (
  `matristu` INT(9) NOT NULL,
  `stunNames` VARCHAR(45) NOT NULL,
  `stuLastNames` VARCHAR(45) NOT NULL,
  `stuSex` VARCHAR(1) NOT NULL,
  `stuAge` INT(2) NOT NULL,
  `stuBithDate` DATE NOT NULL,
  `stuQual` VARCHAR(45) NOT NULL,
  `stuExt` VARCHAR(45) NOT NULL,
  `stuInt` VARCHAR(45) NOT NULL,
  `stuCol` VARCHAR(45) NOT NULL,
  `stuMun` VARCHAR(45) NOT NULL,
  `stuEnti` VARCHAR(45) NOT NULL,
  `stuPostalCode` VARCHAR(45) NOT NULL,
  `stuPhone` VARCHAR(15) NOT NULL,
  `stuCare` VARCHAR(40) NOT NULL,
  `stuSeme` VARCHAR(7) NOT NULL,
  `stuTurn` VARCHAR(10) NOT NULL,
  `stuGroup` INT(4) NOT NULL,
  `stuMail` VARCHAR(45) NOT NULL,
  `stuUser` VARCHAR(45) NOT NULL,
  `stuClav` VARCHAR(45) NOT NULL,
  `stuTipe` VARCHAR(9) NOT NULL,
  `stuRol` INT(1) NOT NULL,
  `stuFere` TIMESTAMP NOT NULL,
  PRIMARY KEY (`matristu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`teachers` (
  `matritea` INT(9) NOT NULL,
  `teachNames` VARCHAR(35) NULL,
  `teachSex` VARCHAR(1) NULL,
  `teachMail` VARCHAR(30) NULL,
  `teachPhone` VARCHAR(15) NOT NULL,
  `teachUser` VARCHAR(25) NOT NULL,
  `teachClue` VARCHAR(45) NOT NULL,
  `teachRol` INT(1) NOT NULL,
  `teachState` VARCHAR(9) NOT NULL,
  `teachFere` TIMESTAMP NULL,
  PRIMARY KEY (`matritea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`admins` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `admNames` VARCHAR(35) NOT NULL,
  `admSex` VARCHAR(1) NOT NULL,
  `admMail` VARCHAR(30) NOT NULL,
  `admPhone` VARCHAR(15) NOT NULL,
  `admUser` VARCHAR(25) NOT NULL,
  `admClue` VARCHAR(45) NOT NULL,
  `admRol` INT(1) NOT NULL,
  `admState` VARCHAR(9) NOT NULL,
  `admFere` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`subjects` (
  `cavsub` INT NOT NULL,
  `subName` VARCHAR(45) NOT NULL,
  `subCol` VARCHAR(45) NOT NULL,
  `subCredit` INT(2) NOT NULL,
  `subHors` TIME NOT NULL,
  PRIMARY KEY (`cavsub`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`hors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`hors` (
  `idhors` INT NOT NULL AUTO_INCREMENT,
  `horsDay` VARCHAR(9) NOT NULL,
  `horStart` TIME NOT NULL,
  `horFinish` TIME NOT NULL,
  `idsubject` INT NOT NULL,
  `idtea` INT NOT NULL,
  `subjects_cavsub` INT NOT NULL,
  `teachers_matritea` INT(9) NOT NULL,
  PRIMARY KEY (`idhors`),
  CONSTRAINT `fk_hors_subjects1`
    FOREIGN KEY (`subjects_cavsub`)
    REFERENCES `proyecto`.`subjects` (`cavsub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hors_teachers1`
    FOREIGN KEY (`teachers_matritea`)
    REFERENCES `proyecto`.`teachers` (`matritea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`courses` (
  `idcourse` INT NOT NULL AUTO_INCREMENT,
  `coursesTipe` VARCHAR(45) NOT NULL,
  `coursesCol` VARCHAR(45) NULL,
  PRIMARY KEY (`idcourse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`academic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`academic` (
  `idacademic` INT NOT NULL AUTO_INCREMENT,
  `idstudent` INT NOT NULL,
  `idsubject` INT NOT NULL,
  `academicGroup` INT(4) NOT NULL,
  `idcourse` INT NOT NULL,
  `students_matristu` INT(9) NOT NULL,
  `subjects_cavsub` INT NOT NULL,
  PRIMARY KEY (`idacademic`),
  CONSTRAINT `idcourse`
    FOREIGN KEY (`idcourse`)
    REFERENCES `proyecto`.`courses` (`idcourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_academic_students1`
    FOREIGN KEY (`students_matristu`)
    REFERENCES `proyecto`.`students` (`matristu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_academic_subjects1`
    FOREIGN KEY (`subjects_cavsub`)
    REFERENCES `proyecto`.`subjects` (`cavsub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`statusProjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`statusProjects` (
  `idstatusProjects` INT NOT NULL,
  `StatusproNames` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idstatusProjects`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Projects` (
  `idProjects` INT NOT NULL,
  `projName` VARCHAR(45) NOT NULL,
  `proDescription` VARCHAR(255) NOT NULL,
  `proFile` VARCHAR(255) NOT NULL,
  `dateprojects` DATE NOT NULL,
  `students_matristu` INT(9) NOT NULL,
  `teachers_matritea` INT(9) NOT NULL,
  `statusProjects_idstatusProjects` INT NOT NULL,
  CONSTRAINT `fk_Projects_students1`
    FOREIGN KEY (`students_matristu` , `idProjects`)
    REFERENCES `proyecto`.`students` (`matristu` , `matristu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_teachers1`
    FOREIGN KEY (`teachers_matritea`)
    REFERENCES `proyecto`.`teachers` (`matritea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_statusProjects1`
    FOREIGN KEY (`statusProjects_idstatusProjects`)
    REFERENCES `proyecto`.`statusProjects` (`idstatusProjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Projects_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Projects_students` (
  `id` INT NOT NULL,
  `idstudent` INT NOT NULL,
  `admins_idadmin` INT NOT NULL,
  `Projects_idProjects` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Projects_students_admins1`
    FOREIGN KEY (`admins_idadmin`)
    REFERENCES `proyecto`.`admins` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_students_Projects1`
    FOREIGN KEY (`Projects_idProjects`)
    REFERENCES `proyecto`.`Projects` (`idProjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Periodo` (
  `idPeriodo` INT NOT NULL AUTO_INCREMENT,
  `perPeriodo` VARCHAR(10) NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `carreNombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `actNombre` VARCHAR(45) NULL,
  `actLimit` INT(9) NULL,
  `Periodo_idPeriodo` INT NOT NULL,
  `carrera_idcarrera` INT NOT NULL,
  `teachers_matritea` INT(9) NOT NULL,
  PRIMARY KEY (`idActividad`),
  CONSTRAINT `fk_Actividad_Periodo1`
    FOREIGN KEY (`Periodo_idPeriodo`)
    REFERENCES `proyecto`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `proyecto`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_teachers1`
    FOREIGN KEY (`teachers_matritea`)
    REFERENCES `proyecto`.`teachers` (`matritea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`subir_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`subir_doc` (
  `idsubir_doc` INT NOT NULL AUTO_INCREMENT,
  `subiNombre` VARCHAR(300) NULL,
  `subiTipo` VARCHAR(45) NULL,
  `subiContenido` BLOB NULL,
  `subipeso` INT NULL,
  `subiFecha` DATETIME NULL,
  `students_matristu` INT(9) NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`idsubir_doc`),
  CONSTRAINT `fk_subir_doc_students1`
    FOREIGN KEY (`students_matristu`)
    REFERENCES `proyecto`.`students` (`matristu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subir_doc_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `proyecto`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Horas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Horas` (
  `idHoras` INT NOT NULL AUTO_INCREMENT,
  `horfecha` DATE NULL,
  `horhoraini` TIME NULL,
  `horhorafin` TIME NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`idHoras`),
  CONSTRAINT `fk_Horas_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `proyecto`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Inscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Inscripciones` (
  `idInscripciones` INT NOT NULL AUTO_INCREMENT,
  `InsAlum` INT NULL,
  `InsLimit` INT NULL,
  `Actividad_idActividad` INT NOT NULL,
  `students_matristu` INT(9) NOT NULL,
  PRIMARY KEY (`idInscripciones`),
  CONSTRAINT `fk_Inscripciones_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `proyecto`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripciones_students1`
    FOREIGN KEY (`students_matristu`)
    REFERENCES `proyecto`.`students` (`matristu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Desempenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Desempenio` (
  `idDesempenio` INT NOT NULL AUTO_INCREMENT,
  `desenombre` VARCHAR(15) NULL,
  `desevalor` INT NULL,
  `Actividad_idActividad` INT NOT NULL,
  `students_matristu` INT(9) NOT NULL,
  PRIMARY KEY (`idDesempenio`),
  CONSTRAINT `fk_Desempenio_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `proyecto`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Desempenio_students1`
    FOREIGN KEY (`students_matristu`)
    REFERENCES `proyecto`.`students` (`matristu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
